POST http://localhost:3000/auth/register/
Content-Type: application/json

{
  "username": "example",
  "email": "example@example.com",
  "password": "1234"
}


###
POST http://localhost:3000/auth/login/
Content-Type: application/json

{
  "username": "example",
  "password": "1234"
}

###
GET http://localhost:3000/posts/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2JkNTk5YTAwYzk1NDYwNTc4MmIzYWIiLCJpYXQiOjE2NzMzNTQ1NDk1MTIsImV4cCI6MTY3MzM1NDYzNTkxMn0.UO1aGSC2Qg5T8fHFG2_VtHcIjragctLOSk4yZLH7oR0

###
POST http://localhost:3000/posts/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2JkNTk5YTAwYzk1NDYwNTc4MmIzYWIiLCJpYXQiOjE2NzMzNTQ1NDk1MTIsImV4cCI6MTY3MzM1NDYzNTkxMn0.UO1aGSC2Qg5T8fHFG2_VtHcIjragctLOSk4yZLH7oR0