POST http://localhost:3000/auth/register/
Content-Type: application/json

{
  "username": "example",
  "email": "example@example.com",
  "password": "1234"
}


###
POST http://localhost:3000/auth/login/
Content-Type: application/json

{
  "username": "example",
  "password": "1234"
}

###
GET http://localhost:3000/posts/
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2JkNTk5YTAwYzk1NDYwNTc4MmIzYWIiLCJpYXQiOjE2NzMzNTM2MjY3ODAsImV4cCI6MTY3MzM1MzcxMzE4MH0.CnWoJRkHN7JLHI2ySxUM7EqXyczYmPv1HfS_9-oCQGA"